/*
 * aida
 *
 * 1.0.704.0
 *
 * The version of the OpenAPI document: 1.0.704.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AddDataSourceConfiguration200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddDataSourceConfiguration200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddDataSourceConfiguration200Response
        //private AddDataSourceConfiguration200Response instance;

        public AddDataSourceConfiguration200ResponseTests()
        {
            // TODO uncomment below to create an instance of AddDataSourceConfiguration200Response
            //instance = new AddDataSourceConfiguration200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddDataSourceConfiguration200Response
        /// </summary>
        [Fact]
        public void AddDataSourceConfiguration200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddDataSourceConfiguration200Response
            //Assert.IsType<AddDataSourceConfiguration200Response>(instance);
        }

        /// <summary>
        /// Test the property 'TableName'
        /// </summary>
        [Fact]
        public void TableNameTest()
        {
            // TODO unit test for the property 'TableName'
        }

        /// <summary>
        /// Test the property 'QueryTemplate'
        /// </summary>
        [Fact]
        public void QueryTemplateTest()
        {
            // TODO unit test for the property 'QueryTemplate'
        }

        /// <summary>
        /// Test the property 'ConnectionString'
        /// </summary>
        [Fact]
        public void ConnectionStringTest()
        {
            // TODO unit test for the property 'ConnectionString'
        }

        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

        /// <summary>
        /// Test the property 'Discriminator'
        /// </summary>
        [Fact]
        public void DiscriminatorTest()
        {
            // TODO unit test for the property 'Discriminator'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DataSourceType'
        /// </summary>
        [Fact]
        public void DataSourceTypeTest()
        {
            // TODO unit test for the property 'DataSourceType'
        }

        /// <summary>
        /// Test the property 'CanBeDeleted'
        /// </summary>
        [Fact]
        public void CanBeDeletedTest()
        {
            // TODO unit test for the property 'CanBeDeleted'
        }
    }
}
