/*
 * aida
 *
 * 1.0.721-rc.9+f020d61fcb6ef6ebe31e8b3974d429a24c2e10d0
 *
 * The version of the OpenAPI document: 1.0.721-rc.9+f020d61fcb6ef6ebe31e8b3974d429a24c2e10d0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Cartridge
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartridgeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Cartridge
        //private Cartridge instance;

        public CartridgeTests()
        {
            // TODO uncomment below to create an instance of Cartridge
            //instance = new Cartridge();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Cartridge
        /// </summary>
        [Fact]
        public void CartridgeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Cartridge
            //Assert.IsType<Cartridge>(instance);
        }

        /// <summary>
        /// Test the property 'CartridgeProductionDate'
        /// </summary>
        [Fact]
        public void CartridgeProductionDateTest()
        {
            // TODO unit test for the property 'CartridgeProductionDate'
        }

        /// <summary>
        /// Test the property 'CartridgeLineSerialNumber'
        /// </summary>
        [Fact]
        public void CartridgeLineSerialNumberTest()
        {
            // TODO unit test for the property 'CartridgeLineSerialNumber'
        }

        /// <summary>
        /// Test the property 'CartridgeInkType'
        /// </summary>
        [Fact]
        public void CartridgeInkTypeTest()
        {
            // TODO unit test for the property 'CartridgeInkType'
        }

        /// <summary>
        /// Test the property 'CartridgeColor'
        /// </summary>
        [Fact]
        public void CartridgeColorTest()
        {
            // TODO unit test for the property 'CartridgeColor'
        }

        /// <summary>
        /// Test the property 'CartridgeInkProductionDate'
        /// </summary>
        [Fact]
        public void CartridgeInkProductionDateTest()
        {
            // TODO unit test for the property 'CartridgeInkProductionDate'
        }

        /// <summary>
        /// Test the property 'CartridgeInkExpireDate'
        /// </summary>
        [Fact]
        public void CartridgeInkExpireDateTest()
        {
            // TODO unit test for the property 'CartridgeInkExpireDate'
        }

        /// <summary>
        /// Test the property 'CartridgeInitialVolume'
        /// </summary>
        [Fact]
        public void CartridgeInitialVolumeTest()
        {
            // TODO unit test for the property 'CartridgeInitialVolume'
        }

        /// <summary>
        /// Test the property 'CartridgeInkConsumption'
        /// </summary>
        [Fact]
        public void CartridgeInkConsumptionTest()
        {
            // TODO unit test for the property 'CartridgeInkConsumption'
        }

        /// <summary>
        /// Test the property 'CartridgeStatus'
        /// </summary>
        [Fact]
        public void CartridgeStatusTest()
        {
            // TODO unit test for the property 'CartridgeStatus'
        }
    }
}
