/*
 * aida
 *
 * 1.0.713
 *
 * The version of the OpenAPI document: 1.0.713
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ClearAfterAutoParkStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClearAfterAutoParkStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClearAfterAutoParkStatus
        //private ClearAfterAutoParkStatus instance;

        public ClearAfterAutoParkStatusTests()
        {
            // TODO uncomment below to create an instance of ClearAfterAutoParkStatus
            //instance = new ClearAfterAutoParkStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClearAfterAutoParkStatus
        /// </summary>
        [Fact]
        public void ClearAfterAutoParkStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClearAfterAutoParkStatus
            //Assert.IsType<ClearAfterAutoParkStatus>(instance);
        }
    }
}
