/*
 * aida
 *
 * 1.0.703.1
 *
 * The version of the OpenAPI document: 1.0.703.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CleaningConfigurationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CleaningConfigurationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CleaningConfigurationDto
        //private CleaningConfigurationDto instance;

        public CleaningConfigurationDtoTests()
        {
            // TODO uncomment below to create an instance of CleaningConfigurationDto
            //instance = new CleaningConfigurationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CleaningConfigurationDto
        /// </summary>
        [Fact]
        public void CleaningConfigurationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CleaningConfigurationDto
            //Assert.IsType<CleaningConfigurationDto>(instance);
        }

        /// <summary>
        /// Test the property 'NormalPurgeDuration'
        /// </summary>
        [Fact]
        public void NormalPurgeDurationTest()
        {
            // TODO unit test for the property 'NormalPurgeDuration'
        }

        /// <summary>
        /// Test the property 'StrongPurgeDuration'
        /// </summary>
        [Fact]
        public void StrongPurgeDurationTest()
        {
            // TODO unit test for the property 'StrongPurgeDuration'
        }

        /// <summary>
        /// Test the property 'WiperPassCount'
        /// </summary>
        [Fact]
        public void WiperPassCountTest()
        {
            // TODO unit test for the property 'WiperPassCount'
        }

        /// <summary>
        /// Test the property 'PumpSpeed'
        /// </summary>
        [Fact]
        public void PumpSpeedTest()
        {
            // TODO unit test for the property 'PumpSpeed'
        }

        /// <summary>
        /// Test the property 'MainSpittingCount'
        /// </summary>
        [Fact]
        public void MainSpittingCountTest()
        {
            // TODO unit test for the property 'MainSpittingCount'
        }

        /// <summary>
        /// Test the property 'MainSpittingFreq'
        /// </summary>
        [Fact]
        public void MainSpittingFreqTest()
        {
            // TODO unit test for the property 'MainSpittingFreq'
        }

        /// <summary>
        /// Test the property 'MainSpittingCycles'
        /// </summary>
        [Fact]
        public void MainSpittingCyclesTest()
        {
            // TODO unit test for the property 'MainSpittingCycles'
        }

        /// <summary>
        /// Test the property 'FinalSpittingCount'
        /// </summary>
        [Fact]
        public void FinalSpittingCountTest()
        {
            // TODO unit test for the property 'FinalSpittingCount'
        }

        /// <summary>
        /// Test the property 'FinalSpittingFreq'
        /// </summary>
        [Fact]
        public void FinalSpittingFreqTest()
        {
            // TODO unit test for the property 'FinalSpittingFreq'
        }

        /// <summary>
        /// Test the property 'FinalSpittingCycles'
        /// </summary>
        [Fact]
        public void FinalSpittingCyclesTest()
        {
            // TODO unit test for the property 'FinalSpittingCycles'
        }

        /// <summary>
        /// Test the property 'InkPrimingTime'
        /// </summary>
        [Fact]
        public void InkPrimingTimeTest()
        {
            // TODO unit test for the property 'InkPrimingTime'
        }

        /// <summary>
        /// Test the property 'VacuumPressureSetPoint'
        /// </summary>
        [Fact]
        public void VacuumPressureSetPointTest()
        {
            // TODO unit test for the property 'VacuumPressureSetPoint'
        }

        /// <summary>
        /// Test the property 'SpittingOffset'
        /// </summary>
        [Fact]
        public void SpittingOffsetTest()
        {
            // TODO unit test for the property 'SpittingOffset'
        }

        /// <summary>
        /// Test the property 'AutoPark'
        /// </summary>
        [Fact]
        public void AutoParkTest()
        {
            // TODO unit test for the property 'AutoPark'
        }

        /// <summary>
        /// Test the property 'AutoClean'
        /// </summary>
        [Fact]
        public void AutoCleanTest()
        {
            // TODO unit test for the property 'AutoClean'
        }

        /// <summary>
        /// Test the property 'CleanAtStartup'
        /// </summary>
        [Fact]
        public void CleanAtStartupTest()
        {
            // TODO unit test for the property 'CleanAtStartup'
        }

        /// <summary>
        /// Test the property 'ClearAfterAutoPark'
        /// </summary>
        [Fact]
        public void ClearAfterAutoParkTest()
        {
            // TODO unit test for the property 'ClearAfterAutoPark'
        }

        /// <summary>
        /// Test the property 'CleanFrequency'
        /// </summary>
        [Fact]
        public void CleanFrequencyTest()
        {
            // TODO unit test for the property 'CleanFrequency'
        }

        /// <summary>
        /// Test the property 'SecondsOfSleepBeforeAutoPark'
        /// </summary>
        [Fact]
        public void SecondsOfSleepBeforeAutoParkTest()
        {
            // TODO unit test for the property 'SecondsOfSleepBeforeAutoPark'
        }
    }
}
