/*
 * aida
 *
 * 1.0.704.0
 *
 * The version of the OpenAPI document: 1.0.704.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DiagnosticActivityState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DiagnosticActivityStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DiagnosticActivityState
        //private DiagnosticActivityState instance;

        public DiagnosticActivityStateTests()
        {
            // TODO uncomment below to create an instance of DiagnosticActivityState
            //instance = new DiagnosticActivityState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DiagnosticActivityState
        /// </summary>
        [Fact]
        public void DiagnosticActivityStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" DiagnosticActivityState
            //Assert.IsType<DiagnosticActivityState>(instance);
        }
    }
}
