/*
 * aida
 *
 * 1.0.703.4
 *
 * The version of the OpenAPI document: 1.0.703.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing HeadAxisPositionFlags
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HeadAxisPositionFlagsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HeadAxisPositionFlags
        //private HeadAxisPositionFlags instance;

        public HeadAxisPositionFlagsTests()
        {
            // TODO uncomment below to create an instance of HeadAxisPositionFlags
            //instance = new HeadAxisPositionFlags();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HeadAxisPositionFlags
        /// </summary>
        [Fact]
        public void HeadAxisPositionFlagsInstanceTest()
        {
            // TODO uncomment below to test "IsType" HeadAxisPositionFlags
            //Assert.IsType<HeadAxisPositionFlags>(instance);
        }
    }
}
