/*
 * aida
 *
 * 1.0.703.4
 *
 * The version of the OpenAPI document: 1.0.703.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PinningSettingsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PinningSettingsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PinningSettingsDto
        //private PinningSettingsDto instance;

        public PinningSettingsDtoTests()
        {
            // TODO uncomment below to create an instance of PinningSettingsDto
            //instance = new PinningSettingsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PinningSettingsDto
        /// </summary>
        [Fact]
        public void PinningSettingsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PinningSettingsDto
            //Assert.IsType<PinningSettingsDto>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Fact]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
    }
}
