/*
 * aida
 *
 * 1.0.703.4
 *
 * The version of the OpenAPI document: 1.0.703.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PrinterStateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrinterStateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrinterStateDto
        //private PrinterStateDto instance;

        public PrinterStateDtoTests()
        {
            // TODO uncomment below to create an instance of PrinterStateDto
            //instance = new PrinterStateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrinterStateDto
        /// </summary>
        [Fact]
        public void PrinterStateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrinterStateDto
            //Assert.IsType<PrinterStateDto>(instance);
        }

        /// <summary>
        /// Test the property 'VacuumPressureMillibar'
        /// </summary>
        [Fact]
        public void VacuumPressureMillibarTest()
        {
            // TODO unit test for the property 'VacuumPressureMillibar'
        }

        /// <summary>
        /// Test the property 'Positions'
        /// </summary>
        [Fact]
        public void PositionsTest()
        {
            // TODO unit test for the property 'Positions'
        }

        /// <summary>
        /// Test the property 'HeadPosition'
        /// </summary>
        [Fact]
        public void HeadPositionTest()
        {
            // TODO unit test for the property 'HeadPosition'
        }

        /// <summary>
        /// Test the property 'TemperatureReadings'
        /// </summary>
        [Fact]
        public void TemperatureReadingsTest()
        {
            // TODO unit test for the property 'TemperatureReadings'
        }

        /// <summary>
        /// Test the property 'VoltageReadings'
        /// </summary>
        [Fact]
        public void VoltageReadingsTest()
        {
            // TODO unit test for the property 'VoltageReadings'
        }

        /// <summary>
        /// Test the property 'TransportStatus'
        /// </summary>
        [Fact]
        public void TransportStatusTest()
        {
            // TODO unit test for the property 'TransportStatus'
        }

        /// <summary>
        /// Test the property 'InkLevelStatus'
        /// </summary>
        [Fact]
        public void InkLevelStatusTest()
        {
            // TODO unit test for the property 'InkLevelStatus'
        }

        /// <summary>
        /// Test the property 'SystemStatus'
        /// </summary>
        [Fact]
        public void SystemStatusTest()
        {
            // TODO unit test for the property 'SystemStatus'
        }

        /// <summary>
        /// Test the property 'DoorsStatus'
        /// </summary>
        [Fact]
        public void DoorsStatusTest()
        {
            // TODO unit test for the property 'DoorsStatus'
        }

        /// <summary>
        /// Test the property 'XAxis'
        /// </summary>
        [Fact]
        public void XAxisTest()
        {
            // TODO unit test for the property 'XAxis'
        }

        /// <summary>
        /// Test the property 'YAxis'
        /// </summary>
        [Fact]
        public void YAxisTest()
        {
            // TODO unit test for the property 'YAxis'
        }
    }
}
