/*
 * aida
 *
 * 1.0.703.2
 *
 * The version of the OpenAPI document: 1.0.703.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PrintStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrintStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrintStatus
        //private PrintStatus instance;

        public PrintStatusTests()
        {
            // TODO uncomment below to create an instance of PrintStatus
            //instance = new PrintStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrintStatus
        /// </summary>
        [Fact]
        public void PrintStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrintStatus
            //Assert.IsType<PrintStatus>(instance);
        }
    }
}
