/*
 * aida
 *
 * 1.0.703.2
 *
 * The version of the OpenAPI document: 1.0.703.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PrintSettingsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrintSettingsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrintSettingsDto
        //private PrintSettingsDto instance;

        public PrintSettingsDtoTests()
        {
            // TODO uncomment below to create an instance of PrintSettingsDto
            //instance = new PrintSettingsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrintSettingsDto
        /// </summary>
        [Fact]
        public void PrintSettingsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrintSettingsDto
            //Assert.IsType<PrintSettingsDto>(instance);
        }

        /// <summary>
        /// Test the property 'JobTemplateInkjetLayoutId'
        /// </summary>
        [Fact]
        public void JobTemplateInkjetLayoutIdTest()
        {
            // TODO unit test for the property 'JobTemplateInkjetLayoutId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'PrintSpeed'
        /// </summary>
        [Fact]
        public void PrintSpeedTest()
        {
            // TODO unit test for the property 'PrintSpeed'
        }

        /// <summary>
        /// Test the property 'VerticalMirrorEnabled'
        /// </summary>
        [Fact]
        public void VerticalMirrorEnabledTest()
        {
            // TODO unit test for the property 'VerticalMirrorEnabled'
        }

        /// <summary>
        /// Test the property 'HorizontalMirrorEnabled'
        /// </summary>
        [Fact]
        public void HorizontalMirrorEnabledTest()
        {
            // TODO unit test for the property 'HorizontalMirrorEnabled'
        }

        /// <summary>
        /// Test the property 'CmykDirectEnabled'
        /// </summary>
        [Fact]
        public void CmykDirectEnabledTest()
        {
            // TODO unit test for the property 'CmykDirectEnabled'
        }

        /// <summary>
        /// Test the property 'EnableC'
        /// </summary>
        [Fact]
        public void EnableCTest()
        {
            // TODO unit test for the property 'EnableC'
        }

        /// <summary>
        /// Test the property 'EnableM'
        /// </summary>
        [Fact]
        public void EnableMTest()
        {
            // TODO unit test for the property 'EnableM'
        }

        /// <summary>
        /// Test the property 'EnableY'
        /// </summary>
        [Fact]
        public void EnableYTest()
        {
            // TODO unit test for the property 'EnableY'
        }

        /// <summary>
        /// Test the property 'EnableK'
        /// </summary>
        [Fact]
        public void EnableKTest()
        {
            // TODO unit test for the property 'EnableK'
        }

        /// <summary>
        /// Test the property 'DropSize'
        /// </summary>
        [Fact]
        public void DropSizeTest()
        {
            // TODO unit test for the property 'DropSize'
        }

        /// <summary>
        /// Test the property 'Multipass'
        /// </summary>
        [Fact]
        public void MultipassTest()
        {
            // TODO unit test for the property 'Multipass'
        }

        /// <summary>
        /// Test the property 'NumberOfPasses'
        /// </summary>
        [Fact]
        public void NumberOfPassesTest()
        {
            // TODO unit test for the property 'NumberOfPasses'
        }

        /// <summary>
        /// Test the property 'DataPageId'
        /// </summary>
        [Fact]
        public void DataPageIdTest()
        {
            // TODO unit test for the property 'DataPageId'
        }
    }
}
