/*
 * aida
 *
 * 1.0.704.0
 *
 * The version of the OpenAPI document: 1.0.704.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SamlightOpticSettingsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SamlightOpticSettingsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SamlightOpticSettingsDto
        //private SamlightOpticSettingsDto instance;

        public SamlightOpticSettingsDtoTests()
        {
            // TODO uncomment below to create an instance of SamlightOpticSettingsDto
            //instance = new SamlightOpticSettingsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SamlightOpticSettingsDto
        /// </summary>
        [Fact]
        public void SamlightOpticSettingsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SamlightOpticSettingsDto
            //Assert.IsType<SamlightOpticSettingsDto>(instance);
        }

        /// <summary>
        /// Test the property 'ApplyDefaultOffsets'
        /// </summary>
        [Fact]
        public void ApplyDefaultOffsetsTest()
        {
            // TODO unit test for the property 'ApplyDefaultOffsets'
        }

        /// <summary>
        /// Test the property 'DefaultOffsetX'
        /// </summary>
        [Fact]
        public void DefaultOffsetXTest()
        {
            // TODO unit test for the property 'DefaultOffsetX'
        }

        /// <summary>
        /// Test the property 'DefaultOffsetY'
        /// </summary>
        [Fact]
        public void DefaultOffsetYTest()
        {
            // TODO unit test for the property 'DefaultOffsetY'
        }

        /// <summary>
        /// Test the property 'DefaultGainX'
        /// </summary>
        [Fact]
        public void DefaultGainXTest()
        {
            // TODO unit test for the property 'DefaultGainX'
        }

        /// <summary>
        /// Test the property 'DefaultGainY'
        /// </summary>
        [Fact]
        public void DefaultGainYTest()
        {
            // TODO unit test for the property 'DefaultGainY'
        }
    }
}
