/*
 * aida
 *
 * 1.0.703.2
 *
 * The version of the OpenAPI document: 1.0.703.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SamLightAxisState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SamLightAxisStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SamLightAxisState
        //private SamLightAxisState instance;

        public SamLightAxisStateTests()
        {
            // TODO uncomment below to create an instance of SamLightAxisState
            //instance = new SamLightAxisState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SamLightAxisState
        /// </summary>
        [Fact]
        public void SamLightAxisStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" SamLightAxisState
            //Assert.IsType<SamLightAxisState>(instance);
        }

        /// <summary>
        /// Test the property 'XInverted'
        /// </summary>
        [Fact]
        public void XInvertedTest()
        {
            // TODO unit test for the property 'XInverted'
        }

        /// <summary>
        /// Test the property 'YInverted'
        /// </summary>
        [Fact]
        public void YInvertedTest()
        {
            // TODO unit test for the property 'YInverted'
        }

        /// <summary>
        /// Test the property 'ZInverted'
        /// </summary>
        [Fact]
        public void ZInvertedTest()
        {
            // TODO unit test for the property 'ZInverted'
        }

        /// <summary>
        /// Test the property 'XyFlipped'
        /// </summary>
        [Fact]
        public void XyFlippedTest()
        {
            // TODO unit test for the property 'XyFlipped'
        }
    }
}
