/*
 * aida
 *
 * 1.0.703.4
 *
 * The version of the OpenAPI document: 1.0.703.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SetReadBackConfiguration200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetReadBackConfiguration200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetReadBackConfiguration200Response
        //private SetReadBackConfiguration200Response instance;

        public SetReadBackConfiguration200ResponseTests()
        {
            // TODO uncomment below to create an instance of SetReadBackConfiguration200Response
            //instance = new SetReadBackConfiguration200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetReadBackConfiguration200Response
        /// </summary>
        [Fact]
        public void SetReadBackConfiguration200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetReadBackConfiguration200Response
            //Assert.IsType<SetReadBackConfiguration200Response>(instance);
        }

        /// <summary>
        /// Test the property 'ReaderAccessType'
        /// </summary>
        [Fact]
        public void ReaderAccessTypeTest()
        {
            // TODO unit test for the property 'ReaderAccessType'
        }

        /// <summary>
        /// Test the property 'ReaderInterfaceType'
        /// </summary>
        [Fact]
        public void ReaderInterfaceTypeTest()
        {
            // TODO unit test for the property 'ReaderInterfaceType'
        }

        /// <summary>
        /// Test the property 'Discriminator'
        /// </summary>
        [Fact]
        public void DiscriminatorTest()
        {
            // TODO unit test for the property 'Discriminator'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ReadBackType'
        /// </summary>
        [Fact]
        public void ReadBackTypeTest()
        {
            // TODO unit test for the property 'ReadBackType'
        }

        /// <summary>
        /// Test the property 'RequiredSide'
        /// </summary>
        [Fact]
        public void RequiredSideTest()
        {
            // TODO unit test for the property 'RequiredSide'
        }

        /// <summary>
        /// Test the property 'JobTemplateId'
        /// </summary>
        [Fact]
        public void JobTemplateIdTest()
        {
            // TODO unit test for the property 'JobTemplateId'
        }

        /// <summary>
        /// Test the property 'HighCoercivity'
        /// </summary>
        [Fact]
        public void HighCoercivityTest()
        {
            // TODO unit test for the property 'HighCoercivity'
        }

        /// <summary>
        /// Test the property 'ReadFromTrack1'
        /// </summary>
        [Fact]
        public void ReadFromTrack1Test()
        {
            // TODO unit test for the property 'ReadFromTrack1'
        }

        /// <summary>
        /// Test the property 'ReadFromTrack2'
        /// </summary>
        [Fact]
        public void ReadFromTrack2Test()
        {
            // TODO unit test for the property 'ReadFromTrack2'
        }

        /// <summary>
        /// Test the property 'ReadFromTrack3'
        /// </summary>
        [Fact]
        public void ReadFromTrack3Test()
        {
            // TODO unit test for the property 'ReadFromTrack3'
        }
    }
}
