/*
 * aida
 *
 * 1.0.721-rc.9+f020d61fcb6ef6ebe31e8b3974d429a24c2e10d0
 *
 * The version of the OpenAPI document: 1.0.721-rc.9+f020d61fcb6ef6ebe31e8b3974d429a24c2e10d0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SmartCardReaderState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SmartCardReaderStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SmartCardReaderState
        //private SmartCardReaderState instance;

        public SmartCardReaderStateTests()
        {
            // TODO uncomment below to create an instance of SmartCardReaderState
            //instance = new SmartCardReaderState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SmartCardReaderState
        /// </summary>
        [Fact]
        public void SmartCardReaderStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" SmartCardReaderState
            //Assert.IsType<SmartCardReaderState>(instance);
        }

        /// <summary>
        /// Test the property 'CurrentState'
        /// </summary>
        [Fact]
        public void CurrentStateTest()
        {
            // TODO unit test for the property 'CurrentState'
        }

        /// <summary>
        /// Test the property 'ReaderName'
        /// </summary>
        [Fact]
        public void ReaderNameTest()
        {
            // TODO unit test for the property 'ReaderName'
        }

        /// <summary>
        /// Test the property 'UpdateCount'
        /// </summary>
        [Fact]
        public void UpdateCountTest()
        {
            // TODO unit test for the property 'UpdateCount'
        }
    }
}
