/*
 * aida
 *
 * 1.0.704.0
 *
 * The version of the OpenAPI document: 1.0.704.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing TemperatureStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemperatureStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemperatureStatus
        //private TemperatureStatus instance;

        public TemperatureStatusTests()
        {
            // TODO uncomment below to create an instance of TemperatureStatus
            //instance = new TemperatureStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemperatureStatus
        /// </summary>
        [Fact]
        public void TemperatureStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemperatureStatus
            //Assert.IsType<TemperatureStatus>(instance);
        }
    }
}
