/*
 * aida
 *
 * 1.0.700.1
 *
 * The version of the OpenAPI document: 1.0.700.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateMatchOccurence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateMatchOccurenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateMatchOccurence
        //private TemplateMatchOccurence instance;

        public TemplateMatchOccurenceTests()
        {
            // TODO uncomment below to create an instance of TemplateMatchOccurence
            //instance = new TemplateMatchOccurence();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateMatchOccurence
        /// </summary>
        [Fact]
        public void TemplateMatchOccurenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateMatchOccurence
            //Assert.IsType<TemplateMatchOccurence>(instance);
        }

        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Fact]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }

        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Fact]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Similarity'
        /// </summary>
        [Fact]
        public void SimilarityTest()
        {
            // TODO unit test for the property 'Similarity'
        }
    }
}
