/*
 * aida
 *
 * 1.0.703.1
 *
 * The version of the OpenAPI document: 1.0.703.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing WorkflowStartedMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkflowStartedMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkflowStartedMessage
        //private WorkflowStartedMessage instance;

        public WorkflowStartedMessageTests()
        {
            // TODO uncomment below to create an instance of WorkflowStartedMessage
            //instance = new WorkflowStartedMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkflowStartedMessage
        /// </summary>
        [Fact]
        public void WorkflowStartedMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkflowStartedMessage
            //Assert.IsType<WorkflowStartedMessage>(instance);
        }
    }
}
