/*
 * aida
 *
 * 1.0.703.1
 *
 * The version of the OpenAPI document: 1.0.703.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing WorkflowSchedulerStopReason
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkflowSchedulerStopReasonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkflowSchedulerStopReason
        //private WorkflowSchedulerStopReason instance;

        public WorkflowSchedulerStopReasonTests()
        {
            // TODO uncomment below to create an instance of WorkflowSchedulerStopReason
            //instance = new WorkflowSchedulerStopReason();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkflowSchedulerStopReason
        /// </summary>
        [Fact]
        public void WorkflowSchedulerStopReasonInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkflowSchedulerStopReason
            //Assert.IsType<WorkflowSchedulerStopReason>(instance);
        }
    }
}
