/*
 * aida
 *
 * 1.0.713
 *
 * The version of the OpenAPI document: 1.0.713
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing XPrintSystemTemperatureStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XPrintSystemTemperatureStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XPrintSystemTemperatureStatus
        //private XPrintSystemTemperatureStatus instance;

        public XPrintSystemTemperatureStatusTests()
        {
            // TODO uncomment below to create an instance of XPrintSystemTemperatureStatus
            //instance = new XPrintSystemTemperatureStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XPrintSystemTemperatureStatus
        /// </summary>
        [Fact]
        public void XPrintSystemTemperatureStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" XPrintSystemTemperatureStatus
            //Assert.IsType<XPrintSystemTemperatureStatus>(instance);
        }
    }
}
