/*
 * aida
 *
 * 1.0.713
 *
 * The version of the OpenAPI document: 1.0.713
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing XPrintCartridgeStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XPrintCartridgeStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XPrintCartridgeStatus
        //private XPrintCartridgeStatus instance;

        public XPrintCartridgeStatusTests()
        {
            // TODO uncomment below to create an instance of XPrintCartridgeStatus
            //instance = new XPrintCartridgeStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XPrintCartridgeStatus
        /// </summary>
        [Fact]
        public void XPrintCartridgeStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" XPrintCartridgeStatus
            //Assert.IsType<XPrintCartridgeStatus>(instance);
        }
    }
}
