/*
 * aida
 *
 * 1.0.721-rc.9+f020d61fcb6ef6ebe31e8b3974d429a24c2e10d0
 *
 * The version of the OpenAPI document: 1.0.721-rc.9+f020d61fcb6ef6ebe31e8b3974d429a24c2e10d0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing XPrintHeadAxisStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XPrintHeadAxisStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XPrintHeadAxisStatus
        //private XPrintHeadAxisStatus instance;

        public XPrintHeadAxisStatusTests()
        {
            // TODO uncomment below to create an instance of XPrintHeadAxisStatus
            //instance = new XPrintHeadAxisStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XPrintHeadAxisStatus
        /// </summary>
        [Fact]
        public void XPrintHeadAxisStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" XPrintHeadAxisStatus
            //Assert.IsType<XPrintHeadAxisStatus>(instance);
        }
    }
}
