/*
 * aida-mini
 *
 * 1.0.713
 *
 * The version of the OpenAPI document: 1.0.713
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing BoxModuleTransportStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BoxModuleTransportStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BoxModuleTransportStatus
        //private BoxModuleTransportStatus instance;

        public BoxModuleTransportStatusTests()
        {
            // TODO uncomment below to create an instance of BoxModuleTransportStatus
            //instance = new BoxModuleTransportStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BoxModuleTransportStatus
        /// </summary>
        [Fact]
        public void BoxModuleTransportStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" BoxModuleTransportStatus
            //Assert.IsType<BoxModuleTransportStatus>(instance);
        }
    }
}
