/*
 * aida-mini
 *
 * 1.0.700.1
 *
 * The version of the OpenAPI document: 1.0.700.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing ChipReadBackMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChipReadBackMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChipReadBackMessage
        //private ChipReadBackMessage instance;

        public ChipReadBackMessageTests()
        {
            // TODO uncomment below to create an instance of ChipReadBackMessage
            //instance = new ChipReadBackMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChipReadBackMessage
        /// </summary>
        [Fact]
        public void ChipReadBackMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChipReadBackMessage
            //Assert.IsType<ChipReadBackMessage>(instance);
        }

        /// <summary>
        /// Test the property 'EncoderIndex'
        /// </summary>
        [Fact]
        public void EncoderIndexTest()
        {
            // TODO unit test for the property 'EncoderIndex'
        }

        /// <summary>
        /// Test the property 'EncoderId'
        /// </summary>
        [Fact]
        public void EncoderIdTest()
        {
            // TODO unit test for the property 'EncoderId'
        }

        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Fact]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }
    }
}
