/*
 * aida-mini
 *
 * 1.0.703.2
 *
 * The version of the OpenAPI document: 1.0.703.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing FeederEmptyMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeederEmptyMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FeederEmptyMessage
        //private FeederEmptyMessage instance;

        public FeederEmptyMessageTests()
        {
            // TODO uncomment below to create an instance of FeederEmptyMessage
            //instance = new FeederEmptyMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FeederEmptyMessage
        /// </summary>
        [Fact]
        public void FeederEmptyMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" FeederEmptyMessage
            //Assert.IsType<FeederEmptyMessage>(instance);
        }
    }
}
