/*
 * aida-mini
 *
 * 1.0.700.1
 *
 * The version of the OpenAPI document: 1.0.700.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing ModulePositionsFlags
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModulePositionsFlagsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModulePositionsFlags
        //private ModulePositionsFlags instance;

        public ModulePositionsFlagsTests()
        {
            // TODO uncomment below to create an instance of ModulePositionsFlags
            //instance = new ModulePositionsFlags();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModulePositionsFlags
        /// </summary>
        [Fact]
        public void ModulePositionsFlagsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModulePositionsFlags
            //Assert.IsType<ModulePositionsFlags>(instance);
        }
    }
}
