/*
 * aida-mini
 *
 * 1.0.704.0
 *
 * The version of the OpenAPI document: 1.0.704.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing PCSCActionResultDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PCSCActionResultDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PCSCActionResultDto
        //private PCSCActionResultDto instance;

        public PCSCActionResultDtoTests()
        {
            // TODO uncomment below to create an instance of PCSCActionResultDto
            //instance = new PCSCActionResultDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PCSCActionResultDto
        /// </summary>
        [Fact]
        public void PCSCActionResultDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PCSCActionResultDto
            //Assert.IsType<PCSCActionResultDto>(instance);
        }

        /// <summary>
        /// Test the property 'DeviceName'
        /// </summary>
        [Fact]
        public void DeviceNameTest()
        {
            // TODO unit test for the property 'DeviceName'
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
    }
}
