/*
 * aida-mini
 *
 * 1.0.703.1
 *
 * The version of the OpenAPI document: 1.0.703.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing PhotoSensorsFlags
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhotoSensorsFlagsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhotoSensorsFlags
        //private PhotoSensorsFlags instance;

        public PhotoSensorsFlagsTests()
        {
            // TODO uncomment below to create an instance of PhotoSensorsFlags
            //instance = new PhotoSensorsFlags();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhotoSensorsFlags
        /// </summary>
        [Fact]
        public void PhotoSensorsFlagsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhotoSensorsFlags
            //Assert.IsType<PhotoSensorsFlags>(instance);
        }
    }
}
