/*
 * aida-mini
 *
 * 1.0.713
 *
 * The version of the OpenAPI document: 1.0.713
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing SystemInfoStatusDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SystemInfoStatusDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SystemInfoStatusDto
        //private SystemInfoStatusDto instance;

        public SystemInfoStatusDtoTests()
        {
            // TODO uncomment below to create an instance of SystemInfoStatusDto
            //instance = new SystemInfoStatusDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SystemInfoStatusDto
        /// </summary>
        [Fact]
        public void SystemInfoStatusDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SystemInfoStatusDto
            //Assert.IsType<SystemInfoStatusDto>(instance);
        }

        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Fact]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }

        /// <summary>
        /// Test the property 'SystemModel'
        /// </summary>
        [Fact]
        public void SystemModelTest()
        {
            // TODO unit test for the property 'SystemModel'
        }

        /// <summary>
        /// Test the property 'IpAddress'
        /// </summary>
        [Fact]
        public void IpAddressTest()
        {
            // TODO unit test for the property 'IpAddress'
        }

        /// <summary>
        /// Test the property 'ServerVersion'
        /// </summary>
        [Fact]
        public void ServerVersionTest()
        {
            // TODO unit test for the property 'ServerVersion'
        }
    }
}
