/*
 * aida
 *
 * 1.0.713
 *
 * The version of the OpenAPI document: 1.0.713
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// Defines ColorName
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ColorName
    {
        /// <summary>
        /// Enum Black for value: Black
        /// </summary>
        [EnumMember(Value = "Black")]
        Black = 1,

        /// <summary>
        /// Enum Cyan for value: Cyan
        /// </summary>
        [EnumMember(Value = "Cyan")]
        Cyan = 2,

        /// <summary>
        /// Enum Magenta for value: Magenta
        /// </summary>
        [EnumMember(Value = "Magenta")]
        Magenta = 3,

        /// <summary>
        /// Enum Yellow for value: Yellow
        /// </summary>
        [EnumMember(Value = "Yellow")]
        Yellow = 4
    }

}
