/*
 * aida
 *
 * 1.0.703.4
 *
 * The version of the OpenAPI document: 1.0.703.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// InkjetMaintenanceStatusDto
    /// </summary>
    [DataContract(Name = "InkjetMaintenanceStatusDto")]
    public partial class InkjetMaintenanceStatusDto : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets TemperatureStatus
        /// </summary>
        [DataMember(Name = "temperatureStatus", EmitDefaultValue = false)]
        public TemperatureStatus? TemperatureStatus { get; set; }

        /// <summary>
        /// Gets or Sets CleanAtStartupStatus
        /// </summary>
        [DataMember(Name = "cleanAtStartupStatus", EmitDefaultValue = false)]
        public CleanAtStartupStatus? CleanAtStartupStatus { get; set; }

        /// <summary>
        /// Gets or Sets ClearAfterAutoParkStatus
        /// </summary>
        [DataMember(Name = "clearAfterAutoParkStatus", EmitDefaultValue = false)]
        public ClearAfterAutoParkStatus? ClearAfterAutoParkStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="InkjetMaintenanceStatusDto" /> class.
        /// </summary>
        /// <param name="temperatureStatus">temperatureStatus.</param>
        /// <param name="cleanAtStartupStatus">cleanAtStartupStatus.</param>
        /// <param name="clearAfterAutoParkStatus">clearAfterAutoParkStatus.</param>
        /// <param name="canPrint">canPrint.</param>
        /// <param name="cantPrintReason">cantPrintReason.</param>
        /// <param name="remainingPrintsBeforeCleaning">remainingPrintsBeforeCleaning.</param>
        /// <param name="remainingTimeBeforeAutoParking">remainingTimeBeforeAutoParking.</param>
        public InkjetMaintenanceStatusDto(TemperatureStatus? temperatureStatus = default(TemperatureStatus?), CleanAtStartupStatus? cleanAtStartupStatus = default(CleanAtStartupStatus?), ClearAfterAutoParkStatus? clearAfterAutoParkStatus = default(ClearAfterAutoParkStatus?), bool canPrint = default(bool), string cantPrintReason = default(string), int remainingPrintsBeforeCleaning = default(int), int remainingTimeBeforeAutoParking = default(int))
        {
            this.TemperatureStatus = temperatureStatus;
            this.CleanAtStartupStatus = cleanAtStartupStatus;
            this.ClearAfterAutoParkStatus = clearAfterAutoParkStatus;
            this.CanPrint = canPrint;
            this.CantPrintReason = cantPrintReason;
            this.RemainingPrintsBeforeCleaning = remainingPrintsBeforeCleaning;
            this.RemainingTimeBeforeAutoParking = remainingTimeBeforeAutoParking;
        }

        /// <summary>
        /// Gets or Sets CanPrint
        /// </summary>
        [DataMember(Name = "canPrint", EmitDefaultValue = true)]
        public bool CanPrint { get; set; }

        /// <summary>
        /// Gets or Sets CantPrintReason
        /// </summary>
        [DataMember(Name = "cantPrintReason", EmitDefaultValue = true)]
        public string CantPrintReason { get; set; }

        /// <summary>
        /// Gets or Sets RemainingPrintsBeforeCleaning
        /// </summary>
        [DataMember(Name = "remainingPrintsBeforeCleaning", EmitDefaultValue = false)]
        public int RemainingPrintsBeforeCleaning { get; set; }

        /// <summary>
        /// Gets or Sets RemainingTimeBeforeAutoParking
        /// </summary>
        [DataMember(Name = "remainingTimeBeforeAutoParking", EmitDefaultValue = false)]
        public int RemainingTimeBeforeAutoParking { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InkjetMaintenanceStatusDto {\n");
            sb.Append("  TemperatureStatus: ").Append(TemperatureStatus).Append("\n");
            sb.Append("  CleanAtStartupStatus: ").Append(CleanAtStartupStatus).Append("\n");
            sb.Append("  ClearAfterAutoParkStatus: ").Append(ClearAfterAutoParkStatus).Append("\n");
            sb.Append("  CanPrint: ").Append(CanPrint).Append("\n");
            sb.Append("  CantPrintReason: ").Append(CantPrintReason).Append("\n");
            sb.Append("  RemainingPrintsBeforeCleaning: ").Append(RemainingPrintsBeforeCleaning).Append("\n");
            sb.Append("  RemainingTimeBeforeAutoParking: ").Append(RemainingTimeBeforeAutoParking).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
