/*
 * aida
 *
 * 1.0.721-rc.9+f020d61fcb6ef6ebe31e8b3974d429a24c2e10d0
 *
 * The version of the OpenAPI document: 1.0.721-rc.9+f020d61fcb6ef6ebe31e8b3974d429a24c2e10d0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// LogFilterablesDto
    /// </summary>
    [DataContract(Name = "LogFilterablesDto")]
    public partial class LogFilterablesDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LogFilterablesDto" /> class.
        /// </summary>
        /// <param name="logLevels">logLevels.</param>
        /// <param name="moduleNames">moduleNames.</param>
        /// <param name="eventTypes">eventTypes.</param>
        public LogFilterablesDto(List<string> logLevels = default(List<string>), List<string> moduleNames = default(List<string>), List<LogEventTypeDto> eventTypes = default(List<LogEventTypeDto>))
        {
            this.LogLevels = logLevels;
            this.ModuleNames = moduleNames;
            this.EventTypes = eventTypes;
        }

        /// <summary>
        /// Gets or Sets LogLevels
        /// </summary>
        [DataMember(Name = "logLevels", EmitDefaultValue = true)]
        public List<string> LogLevels { get; set; }

        /// <summary>
        /// Gets or Sets ModuleNames
        /// </summary>
        [DataMember(Name = "moduleNames", EmitDefaultValue = true)]
        public List<string> ModuleNames { get; set; }

        /// <summary>
        /// Gets or Sets EventTypes
        /// </summary>
        [DataMember(Name = "eventTypes", EmitDefaultValue = true)]
        public List<LogEventTypeDto> EventTypes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LogFilterablesDto {\n");
            sb.Append("  LogLevels: ").Append(LogLevels).Append("\n");
            sb.Append("  ModuleNames: ").Append(ModuleNames).Append("\n");
            sb.Append("  EventTypes: ").Append(EventTypes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
