/*
 * aida
 *
 * 1.0.721-rc.9+f020d61fcb6ef6ebe31e8b3974d429a24c2e10d0
 *
 * The version of the OpenAPI document: 1.0.721-rc.9+f020d61fcb6ef6ebe31e8b3974d429a24c2e10d0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// PrintStatusInfo
    /// </summary>
    [DataContract(Name = "PrintStatusInfo")]
    public partial class PrintStatusInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrintStatusInfo" /> class.
        /// </summary>
        /// <param name="startSignals">startSignals.</param>
        /// <param name="numPrints">numPrints.</param>
        /// <param name="docsFinished">docsFinished.</param>
        /// <param name="docsQueued">docsQueued.</param>
        public PrintStatusInfo(int startSignals = default(int), int numPrints = default(int), int docsFinished = default(int), int docsQueued = default(int))
        {
            this.StartSignals = startSignals;
            this.NumPrints = numPrints;
            this.DocsFinished = docsFinished;
            this.DocsQueued = docsQueued;
        }

        /// <summary>
        /// Gets or Sets StartSignals
        /// </summary>
        [DataMember(Name = "startSignals", EmitDefaultValue = false)]
        public int StartSignals { get; set; }

        /// <summary>
        /// Gets or Sets NumPrints
        /// </summary>
        [DataMember(Name = "numPrints", EmitDefaultValue = false)]
        public int NumPrints { get; set; }

        /// <summary>
        /// Gets or Sets DocsFinished
        /// </summary>
        [DataMember(Name = "docsFinished", EmitDefaultValue = false)]
        public int DocsFinished { get; set; }

        /// <summary>
        /// Gets or Sets DocsQueued
        /// </summary>
        [DataMember(Name = "docsQueued", EmitDefaultValue = false)]
        public int DocsQueued { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PrintStatusInfo {\n");
            sb.Append("  StartSignals: ").Append(StartSignals).Append("\n");
            sb.Append("  NumPrints: ").Append(NumPrints).Append("\n");
            sb.Append("  DocsFinished: ").Append(DocsFinished).Append("\n");
            sb.Append("  DocsQueued: ").Append(DocsQueued).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
