/*
 * aida
 *
 * 1.0.703.4
 *
 * The version of the OpenAPI document: 1.0.703.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// SetReadBackConfiguration200Response
    /// </summary>
    [JsonConverter(typeof(SetReadBackConfiguration200ResponseJsonConverter))]
    [DataContract(Name = "SetReadBackConfiguration_200_response")]
    public partial class SetReadBackConfiguration200Response : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetReadBackConfiguration200Response" /> class
        /// with the <see cref="OcrReadBackConfigurationDto" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of OcrReadBackConfigurationDto.</param>
        public SetReadBackConfiguration200Response(OcrReadBackConfigurationDto actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SetReadBackConfiguration200Response" /> class
        /// with the <see cref="ChipReadBackConfigurationDto" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ChipReadBackConfigurationDto.</param>
        public SetReadBackConfiguration200Response(ChipReadBackConfigurationDto actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SetReadBackConfiguration200Response" /> class
        /// with the <see cref="MagneticReadBackConfigurationDto" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MagneticReadBackConfigurationDto.</param>
        public SetReadBackConfiguration200Response(MagneticReadBackConfigurationDto actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ChipReadBackConfigurationDto) || value is ChipReadBackConfigurationDto)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(MagneticReadBackConfigurationDto) || value is MagneticReadBackConfigurationDto)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(OcrReadBackConfigurationDto) || value is OcrReadBackConfigurationDto)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ChipReadBackConfigurationDto, MagneticReadBackConfigurationDto, OcrReadBackConfigurationDto");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `OcrReadBackConfigurationDto`. If the actual instance is not `OcrReadBackConfigurationDto`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of OcrReadBackConfigurationDto</returns>
        public OcrReadBackConfigurationDto GetOcrReadBackConfigurationDto()
        {
            return (OcrReadBackConfigurationDto)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ChipReadBackConfigurationDto`. If the actual instance is not `ChipReadBackConfigurationDto`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ChipReadBackConfigurationDto</returns>
        public ChipReadBackConfigurationDto GetChipReadBackConfigurationDto()
        {
            return (ChipReadBackConfigurationDto)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MagneticReadBackConfigurationDto`. If the actual instance is not `MagneticReadBackConfigurationDto`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MagneticReadBackConfigurationDto</returns>
        public MagneticReadBackConfigurationDto GetMagneticReadBackConfigurationDto()
        {
            return (MagneticReadBackConfigurationDto)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SetReadBackConfiguration200Response {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, SetReadBackConfiguration200Response.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of SetReadBackConfiguration200Response
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of SetReadBackConfiguration200Response</returns>
        public static SetReadBackConfiguration200Response FromJson(string jsonString)
        {
            SetReadBackConfiguration200Response newSetReadBackConfiguration200Response = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newSetReadBackConfiguration200Response;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ChipReadBackConfigurationDto).GetProperty("AdditionalProperties") == null)
                {
                    newSetReadBackConfiguration200Response = new SetReadBackConfiguration200Response(JsonConvert.DeserializeObject<ChipReadBackConfigurationDto>(jsonString, SetReadBackConfiguration200Response.SerializerSettings));
                }
                else
                {
                    newSetReadBackConfiguration200Response = new SetReadBackConfiguration200Response(JsonConvert.DeserializeObject<ChipReadBackConfigurationDto>(jsonString, SetReadBackConfiguration200Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ChipReadBackConfigurationDto");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ChipReadBackConfigurationDto: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MagneticReadBackConfigurationDto).GetProperty("AdditionalProperties") == null)
                {
                    newSetReadBackConfiguration200Response = new SetReadBackConfiguration200Response(JsonConvert.DeserializeObject<MagneticReadBackConfigurationDto>(jsonString, SetReadBackConfiguration200Response.SerializerSettings));
                }
                else
                {
                    newSetReadBackConfiguration200Response = new SetReadBackConfiguration200Response(JsonConvert.DeserializeObject<MagneticReadBackConfigurationDto>(jsonString, SetReadBackConfiguration200Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("MagneticReadBackConfigurationDto");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MagneticReadBackConfigurationDto: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(OcrReadBackConfigurationDto).GetProperty("AdditionalProperties") == null)
                {
                    newSetReadBackConfiguration200Response = new SetReadBackConfiguration200Response(JsonConvert.DeserializeObject<OcrReadBackConfigurationDto>(jsonString, SetReadBackConfiguration200Response.SerializerSettings));
                }
                else
                {
                    newSetReadBackConfiguration200Response = new SetReadBackConfiguration200Response(JsonConvert.DeserializeObject<OcrReadBackConfigurationDto>(jsonString, SetReadBackConfiguration200Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("OcrReadBackConfigurationDto");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into OcrReadBackConfigurationDto: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newSetReadBackConfiguration200Response;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for SetReadBackConfiguration200Response
    /// </summary>
    public class SetReadBackConfiguration200ResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(SetReadBackConfiguration200Response).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return SetReadBackConfiguration200Response.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return SetReadBackConfiguration200Response.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
