/*
 * aida
 *
 * 1.0.713
 *
 * The version of the OpenAPI document: 1.0.713
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// Defines XPrintTransportAxisStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum XPrintTransportAxisStatus
    {
        /// <summary>
        /// Enum NoErrors for value: NoErrors
        /// </summary>
        [EnumMember(Value = "NoErrors")]
        NoErrors = 1,

        /// <summary>
        /// Enum TransportAxisStepMotorDriverFault for value: TransportAxisStepMotorDriverFault
        /// </summary>
        [EnumMember(Value = "TransportAxisStepMotorDriverFault")]
        TransportAxisStepMotorDriverFault = 2,

        /// <summary>
        /// Enum TransportAxisEjectDcMotorDriverFault for value: TransportAxisEjectDcMotorDriverFault
        /// </summary>
        [EnumMember(Value = "TransportAxisEjectDcMotorDriverFault")]
        TransportAxisEjectDcMotorDriverFault = 3,

        /// <summary>
        /// Enum TransportAxisMotorOrHomePhotoFault for value: TransportAxisMotorOrHomePhotoFault
        /// </summary>
        [EnumMember(Value = "TransportAxisMotorOrHomePhotoFault")]
        TransportAxisMotorOrHomePhotoFault = 4,

        /// <summary>
        /// Enum TransportAxisPositioningFault for value: TransportAxisPositioningFault
        /// </summary>
        [EnumMember(Value = "TransportAxisPositioningFault")]
        TransportAxisPositioningFault = 5,

        /// <summary>
        /// Enum TransportAxisCassetteJamEjectFault for value: TransportAxisCassetteJamEjectFault
        /// </summary>
        [EnumMember(Value = "TransportAxisCassetteJamEjectFault")]
        TransportAxisCassetteJamEjectFault = 6,

        /// <summary>
        /// Enum TransportAxisCassetteJamShuttleClampFault for value: TransportAxisCassetteJamShuttleClampFault
        /// </summary>
        [EnumMember(Value = "TransportAxisCassetteJamShuttleClampFault")]
        TransportAxisCassetteJamShuttleClampFault = 7
    }

}
