/*
 * aida
 *
 * 1.0.713
 *
 * The version of the OpenAPI document: 1.0.713
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// Defines XPrintPrintHeadTemperatureStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum XPrintPrintHeadTemperatureStatus
    {
        /// <summary>
        /// Enum NoErrors for value: NoErrors
        /// </summary>
        [EnumMember(Value = "NoErrors")]
        NoErrors = 1,

        /// <summary>
        /// Enum PrintHeadWarming for value: PrintHeadWarming
        /// </summary>
        [EnumMember(Value = "PrintHeadWarming")]
        PrintHeadWarming = 2,

        /// <summary>
        /// Enum PrintHeadUnderTemperature for value: PrintHeadUnderTemperature
        /// </summary>
        [EnumMember(Value = "PrintHeadUnderTemperature")]
        PrintHeadUnderTemperature = 3,

        /// <summary>
        /// Enum PrintHeadOverTemperature for value: PrintHeadOverTemperature
        /// </summary>
        [EnumMember(Value = "PrintHeadOverTemperature")]
        PrintHeadOverTemperature = 4,

        /// <summary>
        /// Enum PrintHeadTemperatureNotAvailable for value: PrintHeadTemperatureNotAvailable
        /// </summary>
        [EnumMember(Value = "PrintHeadTemperatureNotAvailable")]
        PrintHeadTemperatureNotAvailable = 5,

        /// <summary>
        /// Enum HeaterTemperatureNotAvailable for value: HeaterTemperatureNotAvailable
        /// </summary>
        [EnumMember(Value = "HeaterTemperatureNotAvailable")]
        HeaterTemperatureNotAvailable = 6,

        /// <summary>
        /// Enum HeaterAndCoolingFanDriverFault for value: HeaterAndCoolingFanDriverFault
        /// </summary>
        [EnumMember(Value = "HeaterAndCoolingFanDriverFault")]
        HeaterAndCoolingFanDriverFault = 7
    }

}
