/*
 * aida
 *
 * 1.0.703.4
 *
 * The version of the OpenAPI document: 1.0.703.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Aida.Sdk.Client;
using Aida.Sdk.Api;

namespace Aida.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing JobTemplateApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class JobTemplateApiTests : IDisposable
    {
        private JobTemplateApi instance;

        public JobTemplateApiTests()
        {
            instance = new JobTemplateApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobTemplateApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' JobTemplateApi
            //Assert.IsType<JobTemplateApi>(instance);
        }

        /// <summary>
        /// Test JobtemplateIdGet
        /// </summary>
        [Fact]
        public void JobtemplateIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //string apiVersion = null;
            //instance.JobtemplateIdGet(id, apiVersion);
        }
    }
}
